import Head from 'next/head';
import { Channelbar, Chat, Navbar } from '../components/index';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen">
        <Navbar />
        <Channelbar />
        <Chat />
      </main>
    </>
  );
}
